#!/bin/bash
#PBS -N qg2d_cnn_train
#PBS -q nvgpu
#PBS -l select=1:ncpus=4:ngpus=1:mem=32GB
#PBS -l walltime=12:00:00
#PBS -A UCUB0143
#PBS -j oe
#PBS -o /glade/work/acsubram/GitRepos/real_butterfly_effect/ml/train/qg2d_train.log

cd /glade/work/acsubram/GitRepos/real_butterfly_effect

source /glade/u/home/acsubram/miniconda3/etc/profile.d/conda.sh
conda activate gfd-notebooks

nvidia-smi -L
python -u -c "import torch; print('torch:', torch.__version__); print('CUDA:', torch.cuda.is_available()); [print('GPU:', torch.cuda.get_device_name(i)) for i in range(torch.cuda.device_count())]"

python -u ml/train/train_qg2d.py
